import dynamic from 'next/dynamic';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import AblyChatComponent from '../pages/components/AblyChatComponent'

// const AblyChatComponent = dynamic(
//   () => import("../pages/components/AblyChatComponent"),
//   { ssr: true }
// );

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chatty - Next.js Chat Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next.js Chat Demo</h1>
        <AblyChatComponent />
      </main>
    </div>
  )
}
